[build]
buildCommand = "npm install && npm run build && npx prisma generate"

[deploy]
startCommand = "npx prisma migrate deploy && node dist/main"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
